### ISSUE TITLE
Investigate switching from distutils to setuptools

### ISSUE THREAD

**Issue by ngoldbaum** [cmbruns/pyopenvr#19]
Setuptools has many nice features like "setup.py develop" and will allow you to upload a wheel to pypi along with the source tarball.

Care may need to be taken to handle pep-440 versions, since the current version numbers will be normalized by setuptools.

**Comment by cmbruns-hhmi** [comment]
Using setuptools might require additional restrictions on the version numbers. I think that's why I was using distutils in the first place. So I want to become very lucid about our version number requirements before jumping into this. So, what are our version numbering requirements?

1. Our main distribution portal is PyPi. It appears that PyPi is likely to permit versions that adhere to pep-440. But I'd like to run some tests to be certain.
2. I like to use the bdist_msi installer on Windows, because it integrates well with the Windows package/program install/uninstall system. The MSI installers require, I believe, versions with up to three dot-separated series of digits, e.g. "1.4.109". In particular, they don't allow a "pre" suffix, like I have usually used between releases. This behavior sometimes prevents me from accidentally completing a release without updating the version number. I suspect that using a suffix like "rc0" would have the same effect. Again, I should probably test this conjecture.
3. I have been trying to incorporate the full three-component mainline OpenVR version number into the pyopenvr version number; while appending our own version number into two more digits tacked onto the third component: https://github.com/cmbruns/pyopenvr/wiki/Release-Checklist . From ngoldbaum's pull request at https://github.com/cmbruns/pyopenvr/pull/18, it sounds like leading zeros (like in "1.0.0202") might not remain after setuptools has its way. Question: is there any chance that something might think that "1.0.0202" is a newer version number than "1.0.203"? If not, it's probably OK to migrate to a version format like the latter.

Plus, of course, we would need to test our whole release process using the setuptools version of setup.py before committing to the new way. At least up to the testpypi stage.

**Comment by ngoldbaum** [comment]
For now if you want the same experience as `setup.py develop`, just do `pip install -e .` - pip is actually importing setuptools (which monkeypatches distribute) so this has the same effect (including the version munging.

In response to your question - PEP 440 version strings can be compared with `packaging.version.parse` (see e.g. http://stackoverflow.com/questions/11887762/compare-version-strings)- `packaging` is available on pypi (pip vendors it and uses it internally).

**Comment by cmbruns-hhmi** [comment]
I installed setuptools long ago, so presumably I'm using the monkeypatched distutils in my actual release process. I'm unsure whether it would work as I expect in a vanilla unpatched python install.

**Comment by ngoldbaum** [comment]
Setuptools monkeypatches distutils at import time, not at install time. Just installing setuptools doesn't change anything about your python installation.

**Comment by cmbruns** [comment]
Fixed in issue #24
